project:
  type: website

website:
  title: "Arclight"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: What is Arclight?
        href: projects.qmd
    right:
      - about.qmd
      - icon: github
        href: https://www.linkedin.com/in/learnaboutmattscruggs/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

