project:
  type: website
  output-dir: docs

website:
  favicon: images/arclight-logo.jpg
  navbar:
    logo: images/arclight-logo.jpg
    left:
      - text: Home
        href: index.qmd
      - text: How Arclight Works
        href: projects.qmd
      - text: Project Roadmap
        href: schedule.qmd
    right:
      - text: About
        href: about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/learnaboutmattscruggs/
      - icon: github
        href: https://github.com/MattLScruggs
      - icon: person-vcard
        href: https://mattscruggs.com

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

